package main

type Item struct {
	Name  string  `json:"name"`
	Price float64 `json:"price"`
}

var chipotleMenu = []Item{
	Item{"Burrito (Chicken)", 6.50},
	Item{"Burrito (Steak)", 7.50},
	Item{"Burrito (Carnitas)", 6.95},
	Item{"Burrito (Barbacoa)", 7.50},
	Item{"Burrito (Sofritas)", 6.50},
	Item{"Burrito (Vegetarian)", 6.50},
	Item{"Bowl (Chicken)", 6.50},
	Item{"Bowl (Steak)", 7.50},
	Item{"Bowl (Carnitas)", 6.95},
	Item{"Bowl (Barbacoa)", 7.50},
	Item{"Bowl (Sofritas)", 6.50},
	Item{"Bowl (Vegetarian)", 6.50},
	Item{"Taco (Chicken)", 2.40},
	Item{"Tacos (Chicken)", 6.50},
	Item{"Taco (Steak)", 2.75},
	Item{"Tacos (Steak)", 7.50},
	Item{"Taco (Carnitas)", 2.55},
	Item{"Tacos (Carnitas)", 6.95},
	Item{"Taco (Barbacoa)", 2.75},
	Item{"Tacos (Barbacoa)", 7.50},
	Item{"Taco (Sofritas)", 2.40},
	Item{"Tacos (Sofritas)", 6.50},
	Item{"Taco (Vegetarian)", 2.40},
	Item{"Tacos (Vegetarian)", 6.50},
	Item{"Salad (Chicken)", 6.50},
	Item{"Salad (Steak)", 7.50},
	Item{"Salad (Carnitas)", 6.95},
	Item{"Salad (Barbacoa)", 7.50},
	Item{"Salad (Sofritas)", 6.50},
	Item{"Salad (Vegetarian)", 6.50},
	Item{"Chips & Guacamole", 3.25},
	Item{"Chips & Salsa", 1.95},
	Item{"Guacamole", 1.95},
	Item{"Chips", 1.30},
	Item{"Patron Margarita", 7.15},
	Item{"Sauza Margarita", 4.70},
	Item{"Beer Regular", 3.65},
	Item{"Beer Large", 4.15},
	Item{"Bottled Water", 2.25},
	Item{"Bottled Drink", 2.60},
	Item{"Soda Regular", 1.80},
	Item{"Soda Large", 2.10},
}
